### ISSUE TITLE
Кнопка "Вернуться в каталог"

### ISSUE THREAD

**Issue by Chamber6821** [Wowtika/WordPress#26]
Копия #16
@NikitaKalabin добавь пожалуйста ссылку на ТЗ

**Comment by NikitaKalabin** [comment]
ТЗ по ссылке:
 https://docs.google.com/document/d/1Z9DXyMmWQwCdA6ynpRp1BhYNYIyl6bUe/edit?usp=sharing&ouid=104142740426877061280&rtpof=true&sd=true

**Comment by NikitaKalabin** [comment]
Ссылка на ТЗ https://docs.google.com/document/d/1Z9DXyMmWQwCdA6ynpRp1BhYNYIyl6bUe/edit?usp=sharing&ouid=104142740426877061280&rtpof=true&sd=true
